export const SELLER_LOADING = "SELLER_LOADING";
export const SELLER_LOADED = "SELLER_LOADED";
export const SELLER_AUTH_ERROR = "SELLER_AUTH_ERROR";
export const SELLER_LOGIN_SUCCESS = "SELLER_LOGIN_SUCCESS";
export const SELLER_LOGIN_FAIL = "SELLER_LOGIN_FAIL";
export const SELLER_LOGOUT_SUCCESS = "SELLER_LOGOUT_SUCCESS";
export const SELLER_REGISTER_SUCCESS = "SELLER_REGISTER_SUCCESS";
export const SELLER_REGISTER_FAIL = "SELLER_REGISTER_FAIL";

export const VENDOR_LOADED = "VENDOR_LOADED";
export const VENDOR_LOADING = "VENDOR_LOADING";
export const VENDOR_AUTH_ERROR = "VENDOR_AUTH_ERROR";
export const VENDOR_LOGIN_SUCCESS = "VENDOR_LOGIN_SUCCESS";
export const VENDOR_LOGIN_FAIL = "VENDOR_LOGIN_FAIL";
export const VENDOR_LOGOUT_SUCCESS = "VENDOR_LOGOUT_SUCCESS";
export const VENDOR_REGISTER_SUCCESS = "VENDOR_REGISTER_SUCCESS";
export const VENDOR_REGISTER_FAIL = "VENDOR_REGISTER_FAIL";

export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
